### ISSUE TITLE
혼공 네트워크 질문 드립니다.

### ISSUE THREAD

**Issue by heeyaaaa** [kangtegong/self-learning-cs2#3]
두 번 정독했습니다. 정말 좋은 책 감사드립니다...

심화부분 제외한 질문 드립니다.

1) 이더넷 프레임 헤더 질문입니다.
헤더 중 타입/길이가 1500(05dc(16)) 이하면 프레임의 길이라고 되어있는데, 이더넷 프레임의 페이로드 길이가 1500바이트 이하이며 최대 1500바이트일 경우 전체 프레임 길이는 1500을 초과하니 이 필드가 정확히는 페이로드의 길이를 말하는 것이 아닌지 궁금합니다.

2) ip 클래스리스 주소체계의 CIDR표기법에 대한 질문입니다.
표기법에 대한 이해는 잘 되었습니다.
예로 나와있는 192.168.0.2/25의 경우
네트워크 주소는 192.168.0.0으로, 호스트는 이 네트워크의 2라고 하셨는데
만약 질문이 이 네트워크에서의 호스트ID 를 물어보면 그냥 '2'라고 답할 수 있는 걸까요?
아니면 0.0.0.2이런 식으로 답해야하는 걸까요? 
네트워크 주소 구하는 법은 찾아보면 비슷하게 나오는데 해당 호스트'id'에 대한 정확한 표기법은 찾기 어려워 질문 드립니다.

3) TCP통신에서 three-way handshake에 대한 질문입니다.
three-way handshake는 연결 수립을 위한 과정인데 이 과정에서 TCP세그먼트의 페이로드에는 어떤 정보가 들어가나요?
또한 연결 수립 이후의 순서번호는 three-way handshake에서 주고받았던 초기 순서번호 + a 에서 이어지는 번호가 되는 걸까요?
와이어샤크에서 해당 부분의 패킷을 포착하기 어렵네요...

4) 혼공 네트워크 243/244p의 그림 설명에 대한 질문입니다.
242p의 표를 보면, 혼잡윈도우가 느린시작 임계치에 도달하면 '혼잡윈도우를 절반으로 초기화한 뒤' 혼잡 회피를 수행한다고 설명되어있습니다.
그런데 243p, 244p 의 그래프에서는 느린시작 알고리즘으로 증가하는 혼잡윈도우가 느린시작 임계치에 도달하면(244의 경우 ssthresh1,3) 혼잡윈도우가 절반으로 초기화되는 과정이 나와있지 않아 제가 잘못 이해한 것인지, 혹은 글과 그림 중 어떤 정보가 맞는 것인지 질문드립니다.

5) htttp메서드에 대한 질문입니다.
get메서드 요청 메시지 본문을 포함시키는 것이 바람직하지 않다고 하셨는데, 그 이유는 무엇일까요? 예전에 얕게 개발할 때 오히려 쿼리문자열에 정보를 너무 포함시키면 보안 문제가 있을 수 있다고 들었었는데, 메시지본문보다는 쿼리를 사용하게 되는 이유가 궁금합니다.

**Comment by kangtegong** [comment]
안녕하세요
좋게 읽어주셔서 감사드립니다.

1. 타입/길이에 명시되는 값은 '페이로드의 길이'가 아니라 단일한 숫자입니다. 어떤 숫자가 명시될지는 사전에 정의되어 있습니다.
2. 2번 호스트 혹은 192.168.0.**2**라고 답하시면 됩니다. 후자가 일반적입니다 :) 
3. 페이로드에는 아무 내용도 명시되지 않을 수 있습니다. 처음 연결을 수립할 경우 헤더만 송수신될 수 있습니다. 
4. 아... '절반으로 떨어뜨른다'는 부분은 표기 오타인 것 같습니다. 짚어주셔서 너무 감사드리고 꼼꼼히 봐 주셔서 다시 한 번 감사드립니다. 그래프를 기준으로 학습해 주시면 좋을 것 같습니다.  
5. 말씀하신대로 쿼리 문자열에 비밀번호를 포함시키거나 보안상 민감한 정보를 보내는 것은 바람직하지 않아 다른 메서드를 이용하는 경우가 많습니다. GET 요청의 목적이 '조회'에 가깝기 때문입니다.


감사합니다.
