### ISSUE TITLE
회선 교환방식 질문 드립니다.

### ISSUE THREAD

**Issue by KHG160304** [kangtegong/self-learning-cs2#5]
회선 교환방식의 장점으로, 호스트 사이에 연결을 확보한 후에 메시지를 주고받는 특성에 의해서
전송하는 정보의 양이 일정하다라고 되어있는데,
정보의 양이 일정하다라는 말이 이해가 잘 안됩니다!!
두 호스트 만을 위한 전용로가 설정 되었기 때문에 데이터 유실을 최소화하고 서로 송수신해서 안정적이다라고 이해하면될까요?

**Comment by kangtegong** [comment]
전송률이 비교적으로 일정하다고 이해해주시면 되겠습니다
회선을 공유하는 패킷 교환 방식에서는 두 호스트가 주고받는 정보의 양이 
(다른 호스트가 주고받는 정보에 의해) 들쑥날쑥할 수 있지만
회선 교환은 회선을 점유하기 때문에 전송률이 일정합니다.
