### ISSUE TITLE
p373 TCP 재전송 질문있습니다

### ISSUE THREAD

**Issue by MoonKiHyun** [kangtegong/self-learning-cs2#6]
2번의 패킷에서 3714426508 패킷이 누락되었고 3번의 패킷에서 3714426508 패킷을 다시 요구한 후에

4번에서 3714426508 패킷을 전송해주었는데 왜 5번의 패킷에서 왜 확인 응답 번호가 3714426508 가 되는지 잘 모르겠습니다.

10.10.10.1은 확인 응답 번호가 3714426508인 패킷을 5번이나 보내고,

192.168.0.1은 순서 번호가 3714426508인 패킷을 3번이나 보내는 이유가 궁금합니다.

**Comment by kangtegong** [comment]
안녕하세요
5번의 패킷의 확인 응답 번호(3714426508)는 4번을 수신하기 전에 보낸 것일 가능성이 있습니다.
사실 이 예제에서는 192.168.0.1의 세 번의 재전송을 보이기 위한 예제이므로
5번 패킷은 크게 중요한 예제는 아닙니다^^
2, 4, 6, 8, 9번을 위주로 봐 주세요.
