### ISSUE TITLE
p236 슬라이싱 윈도우 질문합니다

### ISSUE THREAD

**Issue by alrkg** [kangtegong/self-learning-cs2#7]
1. 처음에 1,2,3번째의 세그먼트를 전송하고 ACK를 받은 후 왜 4,5,6 번째의 세그먼트를 보내지 않고 2,3,4번째의 세그먼트를 보내는 건가요?
2. p238 아래의 그림은 분명 4개의 세그먼트를 동시에 보냈는데 확인 응답은 하나밖에 안 오나요?

**Comment by kangtegong** [comment]
안녕하세요, 하나씩 답변드리겠습니다.
1. "2,3,4 를 보낸다"가 아니라 한번에 보낼 수 있는 세그먼트의 범위가 "2,3,4이다"라고 보는 것이 옳습니다.
2. 1번과 같은 맥락입니다. 4개의 세그먼트를 한 번에 보낸 것이 아니라 범위를 표현한 것입니다. "첫 번째 세그먼트에 대한 ACK 세그먼트를 받았다고 가정해 보겠습니다" 라고 표현한 것은 그 때문입니다.

감사합니다.
