### ISSUE TITLE
p256

### ISSUE THREAD

**Issue by alrkg** [kangtegong/self-learning-cs2#8]
FQDN의 첫 번째 부분까지 고려한 도메인 네임이 www.example.com 하나밖에 없다는게 무슨 뜻인지 이해가 잘안됩니다.

**Comment by kangtegong** [comment]
안녕하세요!
호스트는 도메인 네임에 대응되는 IP 주소를 찾기 위해 루트 네임 서버부터 TLD 네임 서버, 2 단계 도메인 네임 서버 ... 순으로 질의하게 됩니다.

예를 들어 www.example.com. 이라는 도메인 네임이 있다고 가정했을 때

1) 가장 우측의 . (루트 도메인)을 먼저 찾고
2) 다음 가장 우측의 .com (TLD)을 다음으로 찾고
3) 다음 가장 우측의 example 을 다음으로 찾고
...
를 반복해 나가는 셈입니다.

이와 같은 방식으로 질의를 반복해 나간다고 가정하면,
호스트가 FQDN의 첫 부분(www)까지 질의한다면
www.exmaple.com.에 대응되는 IP 주소를 응답받을 수 있게 될 것입니다. 

따라서 호스트가 FQDN의 첫 부분(www)까지 질의한다면 원하는 IP 주소를 얻을 수 있게 됩니다.
